FROM centos:7

#整理环境
RUN mkdir -p /www/letsencrypt \
    && ln -s /www/letsencrypt /etc/letsencrypt \
    && rm -f /etc/init.d \
    && mkdir /www/init.d \
    && ln -s /www/init.d /etc/init.d \
    && mkdir /www/wwwroot

#宝塔安装脚本以及wget文件
ADD ./need/wget/* ./

#增加清华源
ADD ./need/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo
 
RUN echo y | bash install.sh

RUN yum clean all

HEALTHCHECK --interval=5s --timeout=3s CMD curl -fs http://localhost:8888/ && curl -fs http://localhost/ || exit 1 
EXPOSE 8888 8888

RUN echo -e "#!/bin/bash\nbt default\nbt start\nwhile true;do sleep 1;done" > entrypoint.sh && chmod +x entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]

