version: "2"
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./db/conf:/etc/mysql/mysql.conf.d
      - ./db/data:/usr/local/mysql/data
      - ./db/logs/:/usr/local/mysql/logs
  confluence:
    container_name: wiki_confluence
    restart: always
    image: cptactionhank/atlassian-confluence:latest
    # image: confluencepublisher/confluence-publisher
    ports:
    - "8090:8090"
    links:
    - mysql:mysql