version: '3'
services:
    postgres:
        image: docker.io/postgres
        environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    sonarqube:
        image: docker.io/sonarqube
        ports:
          - "9000:9000"
        environment:
          SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
          SONARQUBE_JDBC_USERNAME: ${POSTGRES_USER}
          SONARQUBE_JDBC_PASSWORD: ${POSTGRES_PASSWORD}
        links:
          - postgres:postgres
        #sysctls:
        #   vm.max_map_count: 2621441
    pgadmin4:
        image: dpage/pgadmin4
        ports:
            - 8080:80
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PG_USER:-1806620741@qq.com}
            PGADMIN_DEFAULT_PASSWORD: ${PG_PASS:-123456}
