version: '2.0'
services:
    baota:
        image: pch18/baota:clear
        container_name: baota
        restart: always        
        volumes:
            - ./wwwroot/:/www/wwwroot
        network_mode: "host"
        #privileged: true
        #使用该参数，container内的root拥有真正的root权限。
        # 否则，container内的root只是外部的一个普通用户权限。
        # privileged启动的容器，可以看到很多host上的设备，并且可以执行mount。
        # 甚至允许你在docker容器中启动docker容器。
