version: "2.0"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    env_file:
      - redis.env
    restart: always
    volumes:
      - "${REDIS_DIR}/conf:/usr/local/etc/redis"
      - "${REDIS_DIR}/data:/data"